
test:
  description: Perform direct execution of the scheduler rule, for testing the action.
  fields:
    entity_id:
      description: Identifier of the scheduler rule.
      example: "switch.scheduler_abcdef"
    entry:
      description: Index of the entry (for schedules that have multiple entries)
      example: 0

remove:
  description: Remove a scheduler entity
  fields:
    entity_id:
      description: Identifier of the scheduler rule.
      example: "scheduler.scheduler_abcdef"

add:
  description: Add a scheduler entitity
  fields:
    actions:
      description: Action to be executed
      example: '[{service: "turn_on", entity: "light.my_lamp", service_data: {brightness: 200}}]'
    entries:
      description: Entries for entity
      example: '[{time: "12:00", actions: [0]}]'

edit:
  description: Edit a scheduler entitity
  fields:
    entity_id:
      description: Identifier of the scheduler rule.
      example: "scheduler.scheduler_abcdef"
    actions:
      description: Action to be executed
      example: '[{service: "turn_on", entity: "light.my_lamp", service_data: {brightness: 200}}]'
    entries:
      description: Entries for entity
      example: '[{time: "12:00", actions: [0]}]'